### ISSUE TITLE
Not work with other Size of Container or SizedBox

### ISSUE THREAD

**Issue by lexia0611** [rmtmckenzie/flutter_qr_mobile_vision#164]
QR Code will not work (can't read anything) when different size other than 300 x 600 like Example. Tried fit property not work too

**Comment by FMorschel** [comment]
Hi, I've used flutter_qr_mobile_vision for some time and had no problems with size, can you make a minimal reproducible code and run `flutter doctor -v` please?

e.g. I've used this package with [floating_overlay package](https://pub.dev/packages/floating_overlay) and it works just fine. `SizedBox.fromSize` of a fraction of `MediaQuery.of(context).size` (so that the proportions are right) and it worked just fine even scaling.
