### ISSUE TITLE
BarCode Scrambeld

### ISSUE THREAD

**Issue by RickZzDev** [rmtmckenzie/flutter_qr_mobile_vision#165]
I'm trying to read a bar code on itf format, but for some reason, it gives me a scrambeld value and sometimes the right value, i have already defined format to itf

**Comment by vgtle** [comment]
Can you try to use my [fork](https://github.com/rmtmckenzie/flutter_qr_mobile_vision/compare/master...vgtle:master). This could be the reason, because the package internally uses `getRawValue()` instead of `getDisplayValue()`. I wrote about this in my own issue [See here](https://github.com/rmtmckenzie/flutter_qr_mobile_vision/issues/172)

**Comment by RickZzDev** [comment]
I know it was a long time ago, but there was no one poblem with the package. Closing it!
