### ISSUE TITLE
Intense lag when the preview is displayed

### ISSUE THREAD

**Issue by PoolsideKelbi** [rmtmckenzie/flutter_qr_mobile_vision#28]
I am using Samsung Galaxy C7 (2016) and when the camera preview is displayed, the phone experiences serious fps drops.

**Comment by rmtmckenzie** [comment]
Does the flutter part of the app slow down, or is it just the camera view that is low FPS?

One thing you can do to improve the situation slightly is specify the exact type of barcode you're scanning (i.e. QR Code vs PDF417) as by default it scans for all types.

However, the main slowdown right now is actually from encoding the image into the format flutter needs, but it could possibly be improved by switching to receiving a different format from the camera. I'll take a look when I get a chance but it might not be for a while...

**Comment by Galahand** [comment]
i have the same issue with Galaxy S7 Edge SM G935, also the autofocus doesn't seem to work, i tested with the S9+ and it worked well

**Comment by allanwolski** [comment]
same thing here with a Galaxy S5

**Comment by tzinmein** [comment]
Probably related: I'm currently trying to implement this in a project I need to run on older, low-specced devices.

Using Camera2 kills the live preview performance. If I force use the legacy camera API performance is great except the image is flipped 180°, not a huge issue, I can always flip the output around. However the QR code detection does not work for me using the legacy API.

![screenshot_2018-09-20-05-08-44](https://user-images.githubusercontent.com/1826032/45782330-20214380-bc95-11e8-851f-09de1c1c0463.png)

**Comment by rmtmckenzie** [comment]
That's weird it's flipped... assuming you mean rotated 180? I guess I might have made a mistake accounting for the orientation of the camera compared to the device (some of them have the camera module upside down to fit better), so I'll have to look into that. 

The speed issue is something I've been meaning to look into and is because of formats that Camera2 supports (or rather those that it doesn't). At some point I need to just sit down and try different combinations until I figure something out that manages to give me the two formats I need (one for a texture to be shown by flutter and the other for the processing algorithm that looks for QR codes) while still being performant. Sigh =D. 

What's more worrying is that with the Camera1 API it isn't reading the QR codes at all. I have a suspicion that's because you're using a device that supports Camera2 and just disabling it (I've tested it out on a few older devices that only support Camera1), and I didn't take that into account.

I'm really hoping I'll get some time next week to look into this, but there's no guarantees I'll get to it....

**Comment by allanwolski** [comment]
it would be nice to have some progress with that.

related
https://github.com/flutter/flutter/issues/19274

**Comment by rmtmckenzie** [comment]
I've made some changes to how the camera2 version of this works. I've tested on the devices I have and they seem to have much improved performance. If you could test it out and let me know if it works better for you that would be much appreciated @allanwolski, @tzinmein, @Galahand, @PoolsideKelbi

**Comment by Galahand** [comment]
I tested on SM G935F and there is no lag now

**Comment by tzinmein** [comment]
Seems like it works great on the Lenovo A2010 I've been testing on, thank you.

**Comment by allanwolski** [comment]
You did a great job! There is no lag now, but the focus is still a problem.

Do we have to configure autofocus?
It would be interesting an option to activate the flash too.

**Comment by rmtmckenzie** [comment]
I'll close this item as it's resolved now. The focus I'll look into when I get a chance. And if you'd like flash, could you add that as an issue? When I get time I'll look into including it.
