### ISSUE TITLE
Push route on top of scanner, when pop image is freeze

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#31]
Tested I was able to reproduce on the example app, the camera should continue once the screen on top is poped. Currently it freeze and we need to trigger manually a rebuild of the widget to make it work again.

**Comment by rmtmckenzie** [comment]
I've looked into this a bit. However, I don't know that there's actually much I can do in a general sense - flutter doesn't provide any mechanism for detecting when another page has been pushed on top of the current one.

I have added a `restart` method to restart the camera, and made it so that QrCamera can have a key passed in. This would make it so that it's possible to implement something independently from the QrCamera.

There are two ways I could see that working - if your page is simply opening a popup and then closing it, you could wait for that to happen then call restart (you'd have to use a GlobalKey and pass it to QrCamera's constructor...). 

The other way would be a bit more in-depth but could handle more scenarios. You could pass an observer to your Navigator which would observe route changes. When the route changed back to the screen with the QrCamera, you could call restart on it. 

Neither of those solutions is ideal to be honest, but I'm not sure if there's a better way of doing it in flutter.

**Comment by jaumard** [comment]
@rmtmckenzie the new key/restart works perfectly :) thanks a lot ! 
Might worth putting on the Readme or somewhere this limitation, not a big deal as the globalKey solution take 2/3 line more of code ^^

I tried to search also for a built in solution but didn't find anything too

**Comment by rmtmckenzie** [comment]
So I've been thinking about this and the way I did it is not ideal. Could you tell me what you think about this instead @jaumard ?

I'll add an optional parameter 'stopped' to the camera that defaults to false. If that is passed in as true, during the build function I'll cancel the camera if it's running. If it's set back to false, I start the camera again.

The reason I want to do this is that with the current implementation I'm pretty sure the camera is still continuing to take images in the background when you push a page on top of the one with the QrCamera, and that it's just the texture that breaks when you pop which is why you're seeing the frozen image. This way isn't really 100% great either but at least it fixes that and doesn't require a globalKey any more.

**Comment by jaumard** [comment]
Hum I really prefer the GlobalKey solution personally ^^ reason is: after the route is pushed to camera doesn't take picture anymore (I know because the annoying logs I mention earlier are stoping ^^)
And rather that a boolean to stop / start the camera I would rather leave the global key and use stop start restart methods directly when we need. At least no state to manage on our widgets for this. 
It has the same purpose has the boolean in the end but you don't need to wrap into another widget to manage the state.

**Comment by wlans** [comment]
Any updates on this? Running into this problem now.

**Comment by rmtmckenzie** [comment]
The 'restart' method with a globalkey is in the current implementation but isn't documented as it's really more of a stop-gap solution. Since @jaumard was happy with that I never got around to implementing the other solution I proposed, and I don't really like it all that much anyways so I'll try to find a better solution. I don't have time right now to look at this but hopefully sometime in the next week or two my schedule will open up a little.

To use the current fix, make a GlobalKey and pass it to the QrCamera, then after you pop back to your screen call globalKey.state.restart();.

**Comment by Fagnolr** [comment]
Hey @jaumard can you show me your solution please ? 😄

**Comment by jaumard** [comment]
@Fagnolr my solution was to not use this package anymore :D lol

**Comment by Fagnolr** [comment]
Which one do you use? 👼

**Comment by jaumard** [comment]
https://pub.dartlang.org/packages/flutter_camera_ml_vision :)
