### ISSUE TITLE
Suggestion: Change the camera

### ISSUE THREAD

**Issue by felpsio** [rmtmckenzie/flutter_qr_mobile_vision#41]
I'm using the plugin in a tablet and by default it opens the front camera. I would like to use the back camera y default and have the possibility to change during runtime the camera that is being used.

**Comment by rmtmckenzie** [comment]
it should use the back camera by default. Which device are you using, and which version of android?

**Comment by rmtmckenzie** [comment]
I did do a few small changes in the newest version, so if you could check whether you're still seeing the same problem I'd appreciate it.

**Comment by felipecesar42** [comment]
Sorry, the problem was informed wrong. I was testing the tablet problem through a client and I miss understood his feedback. The plugin opens the front camera in tablet and I had to change the native code to open the back camera for my case.

But, stills the suggestion to provide a button or a function that can switch the camera that is being used :)

**Comment by hariprasadiit** [comment]
i think it'd be nice to provide option to switch between front and back cameras as in some use cases QR scanner needs to use front camera.
