### ISSUE TITLE
Issue with dual-camera phones

### ISSUE THREAD

**Issue by NatoBoram** [rmtmckenzie/flutter_qr_mobile_vision#7]
Hello! I tried the plugin on multiple devices and some of them couldn't use it.

Confirmed

* Essential Phone, PH1

Reportedly

* LG X Power
* Some random Samsung tablet

Here's a screenshot taken with an Essential Phone.

![screenshot_20180426-134608](https://user-images.githubusercontent.com/10495562/39323949-299f756e-495c-11e8-9831-df830c0cc768.png)

The camera was pointed at a desk. The computer is under the desk and a a screen and a water bottle are on the desk.

As you can see, the image is severely horizontally stretched. I suspect the dual-camera to be the origin of the issue, though I can't tell for sure because some random other devices apparently also have this problem, and they don't have dual-cameras.

**Comment by rmtmckenzie** [comment]
FYI - I haven't tested it on a tablet at all, so it probably won't work very well. I'll see if I can dig one up to test it on!

**Comment by NatoBoram** [comment]
Tablet performances are horrible so it gets like 1 FPS, but it works on the one I tested

**Comment by rmtmckenzie** [comment]
Ah okay thanks for the info. Sorry but I didn't get a chance to look at it on the weekend after all. I'll do my best in the next couple days but I'm quite busy right now.

I'm guessing the tablet performance is because right now it tries to get the image from the camera at a resolution based on the size of the widget that displays the view. A larger image from the camera => a larger bitmap to process, which makes it slower.

I don't know how much I'll be able to do to alleviate that without lowering the resolution - flutter requires the image in one format while Google Mobile Vision requires it in another, so I'm having to do a conversion regardless of which I choose. I'm fairly sure I already put the processing on a background thread but maybe I can tweak that to make it faster.

Would you happen to know which tablet it is and more importantly which version of Android? I think performance was better with the camera 2 API than the camera 1 API (another fun part of this 😜)

**Comment by rmtmckenzie** [comment]
@NatoBoram I've done an update which should fix your scaling issues, but probably not the performance issues yet.
